// STORY: STORY-016 — Generated reference doc listing every registered error code,
// its description, and its details schema. Regenerated each test run; CI fails if
// docs/MCP-ERROR-CODES.md diverges from the live ErrorCodeRegistry.

import XCTest
@testable import MacOSControlLib

final class ErrorCodesDocumentationGeneratorTests: XCTestCase {

    private static func projectRoot(file: String = #file) -> URL {
        URL(fileURLWithPath: file)
            .deletingLastPathComponent()  // LivingDocumentation/
            .deletingLastPathComponent()  // MCP-MacOSControlTests/
            .deletingLastPathComponent()  // Tests/
            .deletingLastPathComponent()  // <root>/
    }

    func test_writesMcpErrorCodesDoc_andFileIsInSync() throws {
        _ = ErrorCodeRegistry.shared.allRegistrations().count
        let registrations = ErrorCodeRegistry.shared.allRegistrations()
        XCTAssertFalse(registrations.isEmpty, "registry produced no codes — bootstrap failed?")

        let document = Self.render(registrations: registrations)

        let outputFile = Self.projectRoot().appendingPathComponent("docs/MCP-ERROR-CODES.md")
        try FileManager.default.createDirectory(
            at: outputFile.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try document.write(to: outputFile, atomically: true, encoding: .utf8)

        let onDisk = (try? String(contentsOf: outputFile, encoding: .utf8)) ?? ""
        XCTAssertEqual(onDisk, document,
                       "docs/MCP-ERROR-CODES.md is out of sync with ErrorCodeRegistry — run swift test --filter ErrorCodesDocumentationGenerator and commit the result.")
    }

    // MARK: - Markdown rendering

    private static func render(registrations: [ErrorCodeRegistry.Registration]) -> String {
        var md = """
        # MCP Error Codes

        > Generated by `ErrorCodesDocumentationGeneratorTests`. Do not edit by hand.
        > Run `swift test --filter ErrorCodesDocumentationGenerator` to regenerate.

        Every error response emitted by this server uses the wrapped JSON envelope:

        ```json
        {
          "ok": false,
          "error": {
            "code": "<snake_case_code>",
            "message": "<human-readable description>",
            "details": { /* code-specific structured fields */ }
          }
        }
        ```

        Codes are validated at server startup by `ErrorCodeRegistry` to match the regex
        `^[a-z][a-z0-9_]*$` (max 64 chars). Two tools cannot register the same code with
        different semantics — the server refuses to start on collision.

        ## Registered Codes

        | Code | Description | Details fields |
        |---|---|---|

        """
        for reg in registrations {
            let detailsCell: String
            if reg.detailsSchema.isEmpty {
                detailsCell = "—"
            } else {
                detailsCell = reg.detailsSchema
                    .sorted { $0.key < $1.key }
                    .map { "`\($0.key)` (\($0.value))" }
                    .joined(separator: ", ")
            }
            // Strip pipe chars from description to keep the markdown table valid.
            let description = reg.description.replacingOccurrences(of: "|", with: "\\|")
            md += "| `\(reg.code)` | \(description) | \(detailsCell) |\n"
        }

        md += """

        ## Adding a New Code

        1. Add a `registry.register(code: "...", description: "...", detailsSchema: [...])`
           entry in `Sources/MacOSControlLib/StructuredErrors/ErrorCodeBootstrap.swift`.
        2. Use the new code via `MCPErrorResponseBuilder.shared.build(code:message:details:)`.
        3. Run `swift test --filter ErrorCodesDocumentationGenerator` to regenerate this doc.
        4. Commit both the source change and the regenerated doc.

        Collisions (same code, different description) are caught at process startup —
        the server logs both call sites and exits before accepting any request.

        """
        return md
    }
}
