// STORY-012 — End-to-End Integration Validation Suite
//
// Generates docs/LIVING-DOCUMENTATION-INTEGRATION.md from the integration
// feature file and asserts every scenario maps to an integration test —
// mirroring the unit suite's gate so the integration suite gets the same
// "every scenario has an executable proof" guarantee the project values.
//
// It is an IntegrationTestCase subclass, so it only runs (and only writes the
// doc) when CI_MACOS_INTEGRATION=true. The per-PR `ci.yml` `git diff` gate is
// on docs/LIVING-DOCUMENTATION.md (the unit doc) only and is therefore
// untouched by this.

import XCTest

final class IntegrationLivingDocGeneratorTests: IntegrationTestCase {

    func test_writesIntegrationLivingDoc_andEveryScenarioIsMapped() throws {
        let root = Self.projectRoot()
        let featuresDir = root.appendingPathComponent(
            "Tests/MCP-MacOSControlIntegrationTests/Features", isDirectory: true)
        let outputFile = root.appendingPathComponent(
            "docs/LIVING-DOCUMENTATION-INTEGRATION.md")

        let featureURLs = try FileManager.default
            .contentsOfDirectory(at: featuresDir, includingPropertiesForKeys: nil)
            .filter { $0.pathExtension == "feature" }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
        XCTAssertFalse(featureURLs.isEmpty, "no .feature files at \(featuresDir.path)")

        var unmapped: [(file: String, scenario: String)] = []
        var sections: [String] = []
        for url in featureURLs {
            sections.append(try Self.render(
                url: url,
                mapping: IntegrationLivingDocMapping.scenarioToTests,
                unmapped: &unmapped))
        }

        let document = Self.header() + sections.joined()
        try FileManager.default.createDirectory(
            at: outputFile.deletingLastPathComponent(),
            withIntermediateDirectories: true)
        try document.write(to: outputFile, atomically: true, encoding: .utf8)

        if !unmapped.isEmpty {
            let lines = unmapped.map { "  - \($0.file): \"\($0.scenario)\"" }
                .joined(separator: "\n")
            XCTFail("""
            Integration scenarios with no mapped test. Add an entry to \
            IntegrationLivingDocMapping.swift for each:
            \(lines)
            """)
        }
    }

    // MARK: - Helpers (small local copies; the unit generator is in another target)

    private static func projectRoot(file: String = #file) -> URL {
        URL(fileURLWithPath: file)
            .deletingLastPathComponent()  // LivingDocumentation/
            .deletingLastPathComponent()  // MCP-MacOSControlIntegrationTests/
            .deletingLastPathComponent()  // Tests/
            .deletingLastPathComponent()  // <root>/
    }

    private static func header() -> String {
        """
        # Living Documentation — Integration Suite (STORY-012)

        > Generated by `IntegrationLivingDocGeneratorTests`. Do not edit by hand.
        > Regenerate: `CI_MACOS_INTEGRATION=true swift test \
        --filter IntegrationLivingDocGeneratorTests`.

        Each scenario in the integration feature file is listed with the
        integration tests that prove it. The generator fails the build if any
        scenario lacks a mapped test.

        """
    }

    private static func render(
        url: URL,
        mapping: [String: [String]],
        unmapped: inout [(file: String, scenario: String)]
    ) throws -> String {
        let contents = try String(contentsOf: url, encoding: .utf8)
        var title = ""
        var scenarios: [String] = []
        for raw in contents.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = raw.trimmingCharacters(in: .whitespaces)
            if line.hasPrefix("Feature:") {
                title = String(line.dropFirst("Feature:".count))
                    .trimmingCharacters(in: .whitespaces)
            } else if line.hasPrefix("Scenario Outline:") {
                scenarios.append(String(line.dropFirst("Scenario Outline:".count))
                    .trimmingCharacters(in: .whitespaces))
            } else if line.hasPrefix("Scenario:") {
                scenarios.append(String(line.dropFirst("Scenario:".count))
                    .trimmingCharacters(in: .whitespaces))
            }
        }

        var md = "\n## \(title)\n\n"
        md += "*Source: `Tests/MCP-MacOSControlIntegrationTests/Features/\(url.lastPathComponent)`*\n\n"
        for scenario in scenarios {
            md += "### Scenario: \(scenario)\n\n"
            if let tests = mapping[scenario], !tests.isEmpty {
                for t in tests { md += "- `\(t)`\n" }
            } else {
                unmapped.append((file: url.lastPathComponent, scenario: scenario))
                md += "- _**No mapped test — update IntegrationLivingDocMapping.swift.**_\n"
            }
            md += "\n"
        }
        return md
    }
}
