// Generates docs/MCP-TOOL-CATALOG-AUDIT.md by enumerating ToolRouter.allTools
// and rendering an annotation / description-length summary table. The test
// fails the build if any tool is missing annotations or has a description
// shorter than 50 chars — the same DoD checks enforced by ToolCatalogAuditTests
// but framed as a documentation-generation contract.

import XCTest
@testable import MacOSControlLib

final class ToolCatalogAuditReportTests: XCTestCase {

    func test_writesCatalogAudit_andEveryToolPassesDoDChecks() throws {
        let root = Self.projectRoot()
        let outputFile = root.appendingPathComponent("docs/MCP-TOOL-CATALOG-AUDIT.md")

        let tools = ToolRouter.allTools.sorted { $0.name < $1.name }

        var rows: [String] = []
        var failures: [String] = []

        for tool in tools {
            let readOnly = tool.annotations.readOnlyHint
            let destructive = tool.annotations.destructiveHint
            let idempotent = tool.annotations.idempotentHint
            let descriptionLength = tool.description?.count ?? 0

            if tool.annotations.isEmpty {
                failures.append("\(tool.name) has no annotations")
            }
            if readOnly == nil {
                failures.append("\(tool.name) is missing readOnlyHint")
            }
            if destructive == nil {
                failures.append("\(tool.name) is missing destructiveHint")
            }
            if descriptionLength < 50 {
                failures.append("\(tool.name) description is \(descriptionLength) chars (< 50)")
            }

            rows.append(
                "| `\(tool.name)` | \(format(readOnly)) | \(format(destructive)) | \(format(idempotent)) | \(descriptionLength) |"
            )
        }

        let document = Self.header(toolCount: tools.count) + Self.tableHeader + rows.joined(separator: "\n") + "\n"

        try FileManager.default.createDirectory(
            at: outputFile.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try document.write(to: outputFile, atomically: true, encoding: .utf8)

        if !failures.isEmpty {
            XCTFail("""
            STORY-011 tool catalog audit found gaps. Fix the tool definitions in
            Sources/MacOSControlLib/Modules/*.swift, then re-run this test:
            \(failures.map { "  - \($0)" }.joined(separator: "\n"))
            """)
        }
    }

    // MARK: - Helpers

    private func format(_ hint: Bool?) -> String {
        guard let hint else { return "—" }
        return hint ? "true" : "false"
    }

    private static func header(toolCount: Int) -> String {
        """
        # MCP Tool Catalog Audit

        > Generated by `ToolCatalogAuditReportTests`. Do not edit by hand.
        > Run `swift test --filter ToolCatalogAuditReportTests` to regenerate.

        Snapshot of every tool registered in `ToolRouter.allTools`, with its
        `Tool.Annotations` hints and description length. STORY-011's Definition
        of Done requires every tool to declare `readOnlyHint` and
        `destructiveHint`, ship an `idempotentHint`, and have a description of
        at least 50 characters.

        **Total tools:** \(toolCount)

        """
    }

    private static let tableHeader =
        """

        | Tool | readOnlyHint | destructiveHint | idempotentHint | description length |
        |---|---|---|---|---|

        """

    private static func projectRoot(file: String = #file) -> URL {
        // file ≈ <root>/Tests/MCP-MacOSControlTests/Catalog/ToolCatalogAuditReportTests.swift
        URL(fileURLWithPath: file)
            .deletingLastPathComponent()   // Catalog/
            .deletingLastPathComponent()   // MCP-MacOSControlTests/
            .deletingLastPathComponent()   // Tests/
            .deletingLastPathComponent()   // <root>/
    }
}
